version: 0.2

env:
  variables:
    IMAGE_TAG: "dev"

phases:
  install:
    commands:
      - echo "Using custom Go 1.22 Docker image, skipping runtime-versions"
      - cd $CODEBUILD_SRC_DIR
      - echo "Installing Go dependencies"
      - go mod download

  pre_build:
    commands:
      - cd $CODEBUILD_SRC_DIR
      - echo "Running unit tests..."
      # - go test -v -cover ./...
      - echo "Logging into Amazon ECR..."
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_URI
      - echo "Tag = $IMAGE_TAG"

  build:
    commands:
      - cd $CODEBUILD_SRC_DIR
      - echo "Building Docker image..."
      - docker build -t $ECR_URI:$IMAGE_TAG .
      - docker tag $ECR_URI:$IMAGE_TAG $ECR_URI:latest
      - docker push $ECR_URI:$IMAGE_TAG
      - docker push $ECR_URI:latest

  post_build:
    commands:
      - echo "Deploying to ECS..."
      - >
        aws ecs update-service
        --cluster $ECS_CLUSTER
        --service $ECS_SERVICE
        --force-new-deployment
