version: 0.2

env:
  variables:
    IMAGE_TAG: "$CODEBUILD_GIT_BRANCH"

phases:
  pre_build:
    commands:
      - echo Logging into Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION |
        docker login --username AWS --password-stdin $ECR_URI
      - echo Tag = $IMAGE_TAG
  build:
    commands:
      - echo Building Docker image...
      - docker build -t $ECR_URI:$IMAGE_TAG .
      - docker tag $ECR_URI:$IMAGE_TAG $ECR_URI:latest
      - docker push $ECR_URI:$IMAGE_TAG
      - docker push $ECR_URI:latest
  post_build:
    commands:
      - echo Updating ECS service...
      - >
        aws ecs update-service
        --cluster $ECS_CLUSTER
        --service $ECS_SERVICE
        --force-new-deployment
